### ISSUE TITLE
Bug: PR_ID references github issues

### ISSUE THREAD

**Issue by matthias-pichler-shopstory** [karlderkaefer/cdk-notifier#89] opened 2023-05-25 14:12 UTC
Even though the arg is called `--pull-request-id` when using github the notifier tries to add a comment to an issue with the same id instead of the PR

**Comment by jbarrella** [comment] 2023-05-27 00:17
same issue here

**Comment by jbarrella** [comment] 2023-05-31 12:49
Apologies, above was my issue. I supplied an incorrect Github token that did not have access to the correct repository.

**Comment by karlderkaefer** [comment] 2023-06-14 22:46
thanks for report, sorry the delayed answer, somehow I do not get notified on new issues. I was not able to reproduce it locally. However github treats pull requests as a special kind of issue, and the Issues API endpoint is used for actions on both issues and pull requests. From what I have read, issues can not have the same id as the pull request in [stackoverflow](https://stackoverflow.com/questions/63678617/if-i-have-a-github-issue-number-for-a-pull-request-is-that-the-same-as-the-pull) So it's more likely that you somehow used the issue id instead of pr id. So github will redirect to either `/issues` or `/pulls` depending on the id.  can you try a test from your machine? 
```
export REPO_NAME=your-repo
export REPO_OWNER=your-owner
export PR_ID=71
export GITHUB_TOKEN=***
cdk-notifier -l data/cdk-diff1.log --tag-id small
```
anyhow I will double if there are any api changes and also gonna update github client https://github.com/karlderkaefer/cdk-notifier/pull/71

**Comment by karlderkaefer** [comment] 2023-06-29 20:58
@matthias-pichler-shopstory can you describe you get the `--pull-request-id`? in github actions there are [several ways](https://github.com/actions/checkout/issues/58) to get the pull request id

**Comment by karlderkaefer** [comment] 2023-07-09 13:24
PR #98 was merged closing this issue, I could not reproduce. please make sure the PR ID can be found and is valid. Feel free to open reopen the issue and provide more details, from my understanding it is not possible that a PR can have same ID as an Github Issue

**Closed by karlderkaefer** 2023-07-09 13:24 UTC
